#pragma once

// --- LIBRARY SETUP DEFINES ---
#define CANLIB_ADDRESS_LENGTH (29)

#define CANLIB_SYSTEM_ADDRESS_BITS    (5UL)
#define CANLIB_SUBSYSTEM_ADDRESS_BITS (4UL)
#define CANLIB_DEVICE_ADDRESS_BITS    (8UL)
#define CANLIB_GROUP_ADDRESS_BITS     (8UL)
#define CANLIB_PARAM_ADDRESS_BITS     (4UL)

#define CANLIB_PARAM_ADDRESS_POS     0
#define CANLIB_GROUP_ADDRESS_POS     (CANLIB_PARAM_ADDRESS_POS + CANLIB_PARAM_ADDRESS_BITS)
#define CANLIB_DEVICE_ADDRESS_POS    (CANLIB_GROUP_ADDRESS_POS + CANLIB_GROUP_ADDRESS_BITS)
#define CANLIB_SUBSYSTEM_ADDRESS_POS (CANLIB_DEVICE_ADDRESS_POS + CANLIB_DEVICE_ADDRESS_BITS)
#define CANLIB_SYSTEM_ADDRESS_POS    (CANLIB_SUBSYSTEM_ADDRESS_POS + CANLIB_SUBSYSTEM_ADDRESS_BITS)

#define CANLIB_MAX_SYSTEM    ((1UL << CANLIB_SYSTEM_ADDRESS_BITS) - 1)
#define CANLIB_MAX_SUBSYSTEM ((1UL << CANLIB_SUBSYSTEM_ADDRESS_BITS) - 1)
#define CANLIB_MAX_DEVICE    ((1UL << CANLIB_DEVICE_ADDRESS_BITS) - 1)
#define CANLIB_MAX_GROUP     ((1UL << CANLIB_GROUP_ADDRESS_BITS) - 1)
#define CANLIB_MAX_PARAM     ((1UL << CANLIB_PARAM_ADDRESS_BITS) - 1)

#define CANLIB_SYSTEM_TO_BITS(_x)    ((((uint8_t)(_x)) & CANLIB_MAX_SYSTEM) << CANLIB_SYSTEM_ADDRESS_POS)
#define CANLIB_SUBSYSTEM_TO_BITS(_x) ((((uint8_t)(_x)) & CANLIB_MAX_SUBSYSTEM) << CANLIB_SUBSYSTEM_ADDRESS_POS)
#define CANLIB_DEVICE_TO_BITS(_x)    ((((uint8_t)(_x)) & CANLIB_MAX_DEVICE) << CANLIB_DEVICE_ADDRESS_POS)
#define CANLIB_GROUP_TO_BITS(_x)     ((((uint8_t)(_x)) & CANLIB_MAX_GROUP) << CANLIB_GROUP_ADDRESS_POS)
#define CANLIB_PARAM_TO_BITS(_x)     ((((uint8_t)(_x)) & CANLIB_MAX_PARAM) << CANLIB_PARAM_ADDRESS_POS)

#define CANLIB_MAX_PACKET_LENGTH 8

#define CANLIB_ERROR_LENGTH 255

#define CANLIB_NO_ERROR   0
#define CANLIB_NO_HANDLER (nullptr)