#!/usr/bin/env python3
"""
kibisis_space_motor_test.py
Pi 5 test script for the space resources motor (DFRobot DFR0430).
Tests speed and direction via PPM signal generated by the Pico.
"""

import smbus2
import time

SLAVE_ADDR = 0x41
BUS_NUM    = 1

# Register map (must match i2c_slave.hpp)
REG_SPACE_MOTOR_SPEED = 0x02

bus = smbus2.SMBus(BUS_NUM)


def set_space_motor(speed: int):
    """Set space motor speed. Range: -100 (CW) to 0 (stop) to +100 (CCW)."""
    speed = max(-100, min(100, speed))
    bus.write_byte_data(SLAVE_ADDR, REG_SPACE_MOTOR_SPEED, speed & 0xFF)


def stop():
    set_space_motor(0)
    print("  >> Motor stopped")


def run_test(label: str, speed: int, duration: float):
    print(f"  {label}: speed={speed:+4d}%  ({duration}s)")
    set_space_motor(speed)
    time.sleep(duration)


if __name__ == "__main__":
    print("Kibisis Space Resources Motor Test")
    print("===================================")
    print(f"Connecting to 0x{SLAVE_ADDR:02X} on bus {BUS_NUM}...\n")

    try:
        bus.read_byte(SLAVE_ADDR)
    except OSError:
        print(f"ERROR: No device found at 0x{SLAVE_ADDR:02X}. Check wiring and flash.")
        exit(1)

    print("Device found. Starting tests...\n")

    try:
        # --- Clockwise ---
        print("[ Clockwise (negative speed) ]")
        run_test("CW  25%",  -25, 2.0)
        run_test("CW  50%",  -50, 2.0)
        run_test("CW 100%", -100, 2.0)
        stop(); time.sleep(1.0)

        # --- Anticlockwise ---
        print("\n[ Anticlockwise (positive speed) ]")
        run_test("CCW  25%",  25, 2.0)
        run_test("CCW  50%",  50, 2.0)
        run_test("CCW 100%", 100, 2.0)
        stop(); time.sleep(1.0)

        # --- Speed ramp up and down ---
        print("\n[ Ramp up / Ramp down ]")
        print("  Ramping up CCW...")
        for speed in range(0, 101, 10):
            set_space_motor(speed)
            print(f"    {speed:+4d}%")
            time.sleep(0.3)
        print("  Ramping down...")
        for speed in range(100, -1, -10):
            set_space_motor(speed)
            print(f"    {speed:+4d}%")
            time.sleep(0.3)
        stop(); time.sleep(1.0)

        # --- Direction reversal through stop ---
        print("\n[ Direction reversal ]")
        run_test("Full CCW", 100, 2.0)
        stop(); time.sleep(1.0)
        run_test("Full CW", -100, 2.0)
        stop()

        print("\nAll tests complete.")

    except KeyboardInterrupt:
        print("\nTest interrupted.")

    finally:
        stop()
        bus.close()