# Name of the domain bridge, used for node naming and logging
name: autonomy_ros_bridge
from_domain: 51 # ID for Rover domain
to_domain: 42 # ID for Base Station domain
topics:
  # Bridge "/clock" topic from domain ID 51 to domain ID 42
  clock:
    type: rosgraph_msgs/msg/Clock
  # Livox sensor topics
  # livox/imu:
  #   type: sensor_msgs/msg/Imu
  #   qos:
  #     reliability: best_effort
  # livox/lidar:
  #   type: sensor_msgs/msg/PointCloud2
  #   qos:
  #     reliability: best_effort
  # livox/lidar/ground:
  #   type: sensor_msgs/msg/PointCloud2
  #   qos:
  #     reliability: reliable
  # livox/lidar/nonground:
  #   type: sensor_msgs/msg/PointCloud2
  #   qos:
  #     reliability: reliable
  livox/scan:
    type: sensor_msgs/msg/LaserScan
    qos:
      reliability: best_effort
  # Navigation topics
  cmd_vel_out:
    type: geometry_msgs/msg/TwistStamped
    qos:
      reliability: reliable
  odometry/filtered:
    type: nav_msgs/msg/Odometry
    qos:
      reliability: reliable
  plan:
    type: nav_msgs/msg/Path
    qos:
      reliability: reliable
  # Map topics
  map:
    type: nav_msgs/msg/OccupancyGrid
    qos:
      reliability: reliable
  map_updates:
    type: map_msgs/msg/OccupancyGridUpdate
    qos:
      reliability: reliable
  global_costmap/costmap:
    type: nav_msgs/msg/OccupancyGrid
    qos:
      reliability: reliable
  global_costmap/costmap_updates:
    type: map_msgs/msg/OccupancyGridUpdate
    qos:
      reliability: reliable
  # Camera and sensor topics
  rgbd_camera/points:
    type: sensor_msgs/msg/PointCloud2
    qos:
      reliability: best_effort
  robot_description:
    type: std_msgs/msg/String
    qos:
      reliability: reliable
  # System topics
  parameter_events:
    type: rcl_interfaces/msg/ParameterEvent
    qos:
      reliability: reliable
  # Transform topics
  tf:
    type: tf2_msgs/msg/TFMessage
    qos:
      reliability: reliable
  tf_static:
    type: tf2_msgs/msg/TFMessage
    qos:
      reliability: reliable
