name: autonomous_to_main
from_domain: 0  # overridden at launch time
to_domain: 2
topics:
  /livox/scan:
    type: sensor_msgs/msg/LaserScan
    qos:
      reliability: best_effort
  /tf:
    type: tf2_msgs/msg/TFMessage
    qos:
      reliability: reliable
  /tf_static:
    type: tf2_msgs/msg/TFMessage
    qos:
      reliability: reliable