# Automatically generated by: ros2nix --output-dir=ros_ws/nix-packages --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-cmake,
  ament-lint-auto,
  ament-lint-common,
  backward-ros,
  fd-wrapper,
  perseus-interfaces,
  rclcpp,
  std-srvs,
}:
buildRosPackage rec {
  pname = "ros-jazzy-as7343-driver";
  version = "0.0.1";

  src = ./../src/as7343_driver;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  checkInputs = [
    ament-lint-auto
    ament-lint-common
  ];
  propagatedBuildInputs = [
    backward-ros
    fd-wrapper
    perseus-interfaces
    rclcpp
    std-srvs
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "ROS 2 driver for the ams-OSRAM AS7343 14-channel multi-spectral sensor over I2C. Designed for Raspberry Pi 4/5.";
    license = with lib.licenses; [ mit ];
  };
}
