# Automatically generated by: ros2nix --output-dir=/home/james/perseus-v2/Software/ros_ws/nix-packages --output-as-nix-pkg-name --no-default --distro humble
{
  lib,
  buildRosPackage,
  ament-cmake,
  ament-lint-auto,
  ament-lint-common,
  nav2-bringup,
  rclcpp,
  slam-toolbox,
}:
buildRosPackage rec {
  pname = "ros-humble-autonomy";
  version = "0.0.1";

  src = ./../src/autonomy;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  checkInputs = [
    ament-lint-auto
    ament-lint-common
  ];
  propagatedBuildInputs = [
    nav2-bringup
    rclcpp
    slam-toolbox
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "QUTRC Autonomy for robots. Includes Mapping and Localisation based on laserscan and imu data";
    license = with lib.licenses; [ "TODO-License-declaration" ];
  };
}
