# Automatically generated by: ros2nix --output-dir=ros_ws/nix-packages --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-copyright,
  ament-flake8,
  ament-pep257,
  geometry-msgs,
  lifecycle-msgs,
  nav-msgs,
  python3Packages,
  rclpy,
  sensor-msgs,
  std-msgs,
  tf2-ros,
}:
buildRosPackage rec {
  pname = "ros-jazzy-autonomy-diagnostics";
  version = "0.1.0";

  src = ./../src/autonomy_diagnostics;

  buildType = "ament_python";
  checkInputs = [
    ament-copyright
    ament-flake8
    ament-pep257
    python3Packages.pytest
  ];
  propagatedBuildInputs = [
    geometry-msgs
    lifecycle-msgs
    nav-msgs
    python3Packages.pyyaml
    rclpy
    sensor-msgs
    std-msgs
    tf2-ros
  ];

  meta = {
    description = "TUI diagnostic tool for autonomy system monitoring";
    license = with lib.licenses; [ mit ];
  };
}
