# Automatically generated by: ros2nix --output-dir=/home/james/perseus-v2/Software/ros_ws/nix-packages --output-as-nix-pkg-name --no-default --distro humble
{
  lib,
  buildRosPackage,
  ament-cmake,
  ament-lint-auto,
  ament-lint-common,
  rclcpp,
}:
buildRosPackage rec {
  pname = "ros-humble-autonomy";
  version = "0.0.0";

  src = ./../src/autonomy;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  checkInputs = [
    ament-lint-auto
    ament-lint-common
  ];
  propagatedBuildInputs = [ rclcpp ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "TODO: Package description";
    license = with lib.licenses; [ "TODO-License-declaration" ];
  };
}
