# Automatically generated by: ros2nix --output-dir=ros_ws/nix-packages --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-cmake,
  ament-lint-auto,
  ament-lint-common,
  fast-lio,
  navigation2,
  rclcpp,
  robot-localization,
  slam-toolbox,
  watchdog,
  xacro,
}:
buildRosPackage rec {
  pname = "ros-jazzy-autonomy-bringup";
  version = "0.0.1";

  src = ./../src/nav-stack/autonomy_bringup;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  checkInputs = [
    ament-lint-auto
    ament-lint-common
  ];
  propagatedBuildInputs = [
    fast-lio
    navigation2
    rclcpp
    robot-localization
    slam-toolbox
    watchdog
    xacro
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "ROAR autonomy_bringup software control stack";
    license = with lib.licenses; [ mit ];
  };
}
