# Automatically generated by: ros2nix --output-dir=ros_ws/nix-packages --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-cmake,
  rclcpp,
  std-msgs,
}:
buildRosPackage rec {
  pname = "ros-jazzy-deployment-mechanism";
  version = "0.0.1";

  src = ./../src/deployment_mechanism;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  propagatedBuildInputs = [
    rclcpp
    std-msgs
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "Deployment mechanism motor controller for the Perseus rover";
    license = with lib.licenses; [ mit ];
  };
}
