# Automatically generated by: ros2nix --output-dir=ros_ws/nix-packages --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-cmake,
  ament-lint-auto,
  ament-lint-common,
  geometry-msgs,
  rclcpp,
  tf2,
  tf2-geometry-msgs,
  tf2-ros,
}:
buildRosPackage rec {
  pname = "ros-jazzy-footprint-broadcaster";
  version = "0.0.1";

  src = ./../src/nav-stack/footprint_broadcaster;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  checkInputs = [
    ament-lint-auto
    ament-lint-common
  ];
  propagatedBuildInputs = [
    geometry-msgs
    rclcpp
    tf2
    tf2-geometry-msgs
    tf2-ros
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "Broadcasts a ground-plane-flattened base_footprint frame for nav2";
    license = with lib.licenses; [ mit ];
  };
}
