# Automatically generated by: ros2nix --output-dir=ros_ws/nix-packages --output-as-nix-pkg-name --no-default --distro humble
{
  lib,
  buildRosPackage,
  ament-cmake,
  ament-lint-auto,
  ament-lint-common,
  hi-can-lib,
}:
buildRosPackage rec {
  pname = "ros-humble-hardware-interfaces";
  version = "0.0.0";

  src = ./../src/hardware_interfaces;

  buildType = "ament_cmake";
  buildInputs = [
    ament-cmake
    hi-can-lib
  ];
  checkInputs = [
    ament-lint-auto
    ament-lint-common
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "TODO: Package description";
    license = with lib.licenses; [ "TODO-License-declaration" ];
  };
}
