# Automatically generated by: ros2nix --output-dir=ros_ws/nix-packages --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-cmake,
  backward-ros,
  fd-wrapper,
  geometry-msgs,
  hardware-interface,
  rclcpp,
  rclcpp-lifecycle,
  sensor-msgs,
  tf2,
  tf2-geometry-msgs,
}:
buildRosPackage rec {
  pname = "ros-jazzy-i2c-imu-driver";
  version = "0.0.1";

  src = ./../src/perseus_sensors/i2c_imu_driver;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  propagatedBuildInputs = [
    backward-ros
    fd-wrapper
    geometry-msgs
    hardware-interface
    rclcpp
    rclcpp-lifecycle
    sensor-msgs
    tf2
    tf2-geometry-msgs
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "ROS 2 package for I2C IMU sensor driver. Provides direct I2C communication with IMU sensors connected to the host system's I2C bus, publishes sensor_msgs/Imu messages, and integrates with hardware_interface for optional sensor support.";
    license = with lib.licenses; [ mit ];
  };
}
