# Automatically generated by: ros2nix --output-dir=/home/james/perseus-v2/Software/ros_ws/nix-packages --output-as-nix-pkg-name --no-default --distro humble
{
  lib,
  buildRosPackage,
  ament-copyright,
  ament-flake8,
  ament-pep257,
  pythonPackages,
}:
buildRosPackage rec {
  pname = "ros-humble-input-controllers";
  version = "0.0.0";

  src = ./../src/input_devices;

  buildType = "ament_python";
  checkInputs = [
    ament-copyright
    ament-flake8
    ament-pep257
    pythonPackages.pytest
  ];

  meta = {
    description = "TODO: Package description";
    license = with lib.licenses; [ "TODO-License-declaration" ];
  };
}
