# Automatically generated by: ros2nix --output-dir=ros_ws/nix-packages --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-cmake,
  ament-lint-auto,
  ament-lint-common,
  joint-state-publisher,
  joint-state-publisher-gui,
  robot-state-publisher,
  rviz2,
  urdf,
  xacro,
}:
buildRosPackage rec {
  pname = "ros-jazzy-kibisis-description";
  version = "0.1.0";

  src = ./../src/kibisis_description;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  checkInputs = [
    ament-lint-auto
    ament-lint-common
  ];
  propagatedBuildInputs = [
    joint-state-publisher
    joint-state-publisher-gui
    robot-state-publisher
    rviz2
    urdf
    xacro
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "Package containing URDF description for Kibisis robot - a two-wheel differential drive robot";
    license = with lib.licenses; [ mit ];
  };
}
