# Automatically generated by: ros2nix --output-dir=ros_ws/nix-packages --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-cmake,
  controller-manager-msgs,
  rclcpp,
  std-msgs,
  std-srvs,
}:
buildRosPackage rec {
  pname = "ros-jazzy-kibisis-sensors";
  version = "0.1.0";

  src = ./../src/kibisis_sensors;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  propagatedBuildInputs = [
    controller-manager-msgs
    rclcpp
    std-msgs
    std-srvs
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "Standalone ROS2 node bridging ROS2 topics and services to the Kibisis
    space motor and moisture sensor GPIO interfaces in ros2_control.";
    license = with lib.licenses; [ mit ];
  };
}
