# Automatically generated by: ros2nix --output-dir=ros_ws/nix-packages --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-cmake,
  ament-lint-auto,
  ament-lint-common,
  hardware-interface,
  pluginlib,
  rclcpp,
  rclcpp-lifecycle,
}:
buildRosPackage rec {
  pname = "ros-jazzy-kibisis-hardware";
  version = "0.1.0";

  src = ./../src/kibisis_hardware;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  checkInputs = [
    ament-lint-auto
    ament-lint-common
  ];
  propagatedBuildInputs = [
    hardware-interface
    pluginlib
    rclcpp
    rclcpp-lifecycle
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "Hardware interface for Kibisis robot - GPIO-based motor control for Raspberry Pi";
    license = with lib.licenses; [ mit ];
  };
}
