# Automatically generated by: ros2nix --output-dir=ros_ws/nix-packages --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-copyright,
  ament-flake8,
  ament-pep257,
  cv-bridge,
  geometry-msgs,
  nav-msgs,
  python3Packages,
  rclpy,
  robot-localization,
  sensor-msgs,
  slam-toolbox,
  std-msgs,
  tf2-ros,
}:
buildRosPackage rec {
  pname = "ros-jazzy-mapping-autotune";
  version = "0.1.0";

  src = ./../src/mapping_autotune;

  buildType = "ament_python";
  checkInputs = [
    ament-copyright
    ament-flake8
    ament-pep257
    python3Packages.pytest
  ];
  propagatedBuildInputs = [
    cv-bridge
    geometry-msgs
    nav-msgs
    rclpy
    robot-localization
    sensor-msgs
    slam-toolbox
    std-msgs
    tf2-ros
  ];

  meta = {
    description = "Automated SLAM parameter tuning for mapping quality optimization";
    license = with lib.licenses; [ mit ];
  };
}
