# Automatically generated by: ros2nix --output-dir=ros_ws/nix-packages --output-as-nix-pkg-name --no-default --distro jazzy
{ lib, buildRosPackage, ament-cmake, ament-lint-auto, ament-lint-common, builtin-interfaces, geometry-msgs, nav-msgs, nav2-msgs, perseus-interfaces, rclcpp, rclcpp-action, tf2, tf2-ros, visualization-msgs }:
buildRosPackage rec {
  pname = "ros-jazzy-network-recovery";
  version = "0.1.0";

  src = ./../src/network_recovery;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  checkInputs = [ ament-lint-auto ament-lint-common ];
  propagatedBuildInputs = [ builtin-interfaces geometry-msgs nav-msgs nav2-msgs perseus-interfaces rclcpp rclcpp-action tf2 tf2-ros visualization-msgs ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "Network recovery node with WiFi heatmap, signal leash, and autonomous recovery navigation";
    license = with lib.licenses; [ mit ];
  };
}
