# Automatically generated by: ros2nix --output-dir=ros_ws/nix-packages --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-cmake,
  backward-ros,
  perseus-description,
  perseus-hardware,
  rclcpp,
  ros-gz-bridge,
  ros-gz-interfaces,
  ros-gz-sim,
}:
buildRosPackage rec {
  pname = "ros-jazzy-perseus-simulation";
  version = "0.0.1";

  src = ./../src/perseus_simulation;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  propagatedBuildInputs = [
    backward-ros
    perseus-description
    perseus-hardware
    rclcpp
    ros-gz-bridge
    ros-gz-interfaces
    ros-gz-sim
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "ROS 2 package for simulating Perseus with Gazebo Fortress.";
    license = with lib.licenses; [ mit ];
  };
}
