# Automatically generated by: ros2nix --output-dir=ros_ws/nix-packages --output-as-nix-pkg-name --no-default --distro humble
{ lib, buildRosPackage, ament-cmake }:
buildRosPackage rec {
  pname = "ros-humble-perseus-description";
  version = "0.0.1";

  src = ./../src/perseus_description;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "Package containing description files for Perseus V2";
    license = with lib.licenses; [ "TODO-License-declaration" ];
  };
}
