# Automatically generated by: ros2nix --output-dir=ros_ws/nix-packages --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  actuator-msgs,
  ament-cmake,
  backward-ros,
  hardware-interface,
  hi-can-raw,
  moveit-core,
  moveit-ros-move-group,
  moveit-ros-planning-interface,
  moveit-servo,
  moveit-visual-tools,
  perseus-msgs,
  pluginlib,
  rclcpp,
  rclcpp-lifecycle,
  ros2-control,
  ros2-controllers,
  rviz2,
  sensor-msgs,
  std-msgs,
}:
buildRosPackage rec {
  pname = "ros-jazzy-perseus-payloads";
  version = "0.0.1";

  src = ./../src/perseus_payloads;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  propagatedBuildInputs = [
    actuator-msgs
    backward-ros
    hardware-interface
    hi-can-raw
    moveit-core
    moveit-ros-move-group
    moveit-ros-planning-interface
    moveit-servo
    moveit-visual-tools
    perseus-msgs
    pluginlib
    rclcpp
    rclcpp-lifecycle
    ros2-control
    ros2-controllers
    rviz2
    sensor-msgs
    std-msgs
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "Payload-specific nodes and launch files for the Perseus Rover.";
    license = with lib.licenses; [ mit ];
  };
}
