# Automatically generated by: ros2nix --output-dir=ros_ws/nix-packages --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-cmake,
  ament-lint-auto,
  ament-lint-common,
  domain-bridge,
  launch,
  launch-ros,
  libyaml-cpp-dev,
  nav-msgs,
  rclcpp,
  rclcpp-components,
  sensor-msgs,
  std-msgs,
  tf2-msgs,
}:
buildRosPackage rec {
  pname = "ros-jazzy-perseus-domain-bridge";
  version = "0.0.0";

  src = ./../src/perseus_domain_bridge;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  checkInputs = [
    ament-lint-auto
    ament-lint-common
  ];
  propagatedBuildInputs = [
    domain-bridge
    launch
    launch-ros
    libyaml-cpp-dev
    nav-msgs
    rclcpp
    rclcpp-components
    sensor-msgs
    std-msgs
    tf2-msgs
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "Extends ros2/domain_bridge with per-topic Hz rate-limiting.
    Topics can be bridged from one ROS 2 DDS domain to another at a
    configurable maximum rate, reducing bandwidth without requiring
    separate throttle nodes.";
    license = with lib.licenses; [ mit ];
  };
}
