# Automatically generated by: ros2nix --output-dir=ros_ws/nix-packages --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-copyright,
  ament-flake8,
  ament-pep257,
  perseus-interfaces,
  python3Packages,
  std-srvs,
}:
buildRosPackage rec {
  pname = "ros-jazzy-perseus-ilmenite-ml";
  version = "0.0.0";

  src = ./../src/perseus_ilmenite_ml;

  buildType = "ament_python";
  checkInputs = [
    ament-copyright
    ament-flake8
    ament-pep257
    python3Packages.pytest
  ];
  propagatedBuildInputs = [
    perseus-interfaces
    std-srvs
  ];

  meta = {
    description = "TODO: Package description";
    license = with lib.licenses; [ mit ];
  };
}
