# Automatically generated by: ros2nix --output-dir=ros_ws/nix-packages --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-cmake,
  geometry-msgs,
  gz-ros2-control,
  perseus,
  ros-gz-bridge,
  ros-gz-image,
  ros-gz-interfaces,
  ros-gz-sim,
  tf2,
  tf2-ros,
}:
buildRosPackage rec {
  pname = "ros-jazzy-perseus-simulation";
  version = "0.0.1";

  src = ./../src/perseus_simulation;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  propagatedBuildInputs = [
    geometry-msgs
    gz-ros2-control
    perseus
    ros-gz-bridge
    ros-gz-image
    ros-gz-interfaces
    ros-gz-sim
    tf2
    tf2-ros
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "Package for simulating the Perseus rover using Gazebo.";
    license = with lib.licenses; [ mit ];
  };
}
