# Automatically generated by: ros2nix --output-dir=ros_ws/nix-packages --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
<<<<<<< HEAD
  ament-cmake,
  backward-ros,
  hi-can-raw,
  nlohmann_json,
=======
  actuator-msgs,
  ament-cmake,
  backward-ros,
  hi-can-raw,
>>>>>>> eef4c7e (chore: nix-packages)
  rclcpp,
  sensor-msgs,
}:
buildRosPackage rec {
  pname = "ros-jazzy-perseus-can-if";
  version = "0.0.1";

  src = ./../src/perseus_can_if;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  propagatedBuildInputs = [
<<<<<<< HEAD
    backward-ros
    hi-can-raw
    nlohmann_json
=======
    actuator-msgs
    backward-ros
    hi-can-raw
>>>>>>> eef4c7e (chore: nix-packages)
    rclcpp
    sensor-msgs
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "Payload-specific nodes and launch files for the Perseus Rover.";
    license = with lib.licenses; [ mit ];
  };
}
