# Automatically generated by: ros2nix --output-dir=ros_ws/nix-packages --output-as-nix-pkg-name --no-default --distro jazzy
{ lib, buildRosPackage, ament-cmake, ament-lint-auto, ament-lint-common, cv-bridge, geometry-msgs, image-transport, opencv, rclcpp, sensor-msgs, tf2, tf2-ros }:
buildRosPackage rec {
  pname = "ros-jazzy-perseus-vision";
  version = "0.0.0";

  src = ./../src/perseus_vision;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  checkInputs = [ ament-lint-auto ament-lint-common ];
  propagatedBuildInputs = [ cv-bridge geometry-msgs image-transport opencv rclcpp sensor-msgs tf2 tf2-ros ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "A package to do visionary tasks of Perseus";
    license = with lib.licenses; [ mit ];
  };
}
