# Automatically generated by: ros2nix --output-dir=ros_ws/nix-packages --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-cmake,
  backward-ros,
  cv-bridge,
  geometry-msgs,
  image-transport,
  libpcl-dev,
  librealsense2-dev,
  nlohmann_json,
  opencv,
  openssl,
  pcl-conversions,
  rclcpp,
  realsense2-camera,
  realsense2-description,
  sensor-msgs,
  simple-networking,
  tf2-geometry-msgs,
  tf2-ros,
}:
buildRosPackage rec {
  pname = "ros-jazzy-perseus-sensors";
  version = "1.0.0";

  src = ./../src/perseus_sensors;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  propagatedBuildInputs = [
    backward-ros
    cv-bridge
    geometry-msgs
    image-transport
    libpcl-dev
    librealsense2-dev
    nlohmann_json
    opencv
    opencv.cxxdev
    openssl
    pcl-conversions
    rclcpp
    realsense2-camera
    realsense2-description
    sensor-msgs
    simple-networking
    tf2-geometry-msgs
    tf2-ros
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "ROS 2 package for managing and processing point-cloud data from the Slamtec M2M2 lidar device which is accessed by TCP ethernet. Handles network access, data processing and provides ROS sensor message information.";
    license = with lib.licenses; [ mit ];
  };
}
