# Automatically generated by: ros2nix --output-dir=ros_ws/nix-packages --output-as-nix-pkg-name --no-default --distro jazzy
{ lib, buildRosPackage, ament-copyright, ament-flake8, ament-pep257, geometry-msgs, perseus-interfaces, python3Packages, rclpy, sensor-msgs, std-msgs }:
buildRosPackage rec {
  pname = "ros-jazzy-perseus-lite-voice";
  version = "0.1.0";

  src = ./../src/perseus_lite_voice;

  buildType = "ament_python";
  checkInputs = [ ament-copyright ament-flake8 ament-pep257 python3Packages.pytest ];
  propagatedBuildInputs = [ geometry-msgs perseus-interfaces rclpy sensor-msgs std-msgs ];

  meta = {
    description = "Local voice chat system for Perseus Lite with wake word, STT, LLM, and TTS";
    license = with lib.licenses; [ mit ];
  };
}
