# Automatically generated by: ros2nix --output-dir=ros_ws/nix-packages --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  actuator-msgs,
  ament-copyright,
  ament-flake8,
  ament-pep257,
  perseus-interfaces,
  python3Packages,
  rclpy,
  sensor-msgs,
  std-msgs,
}:
buildRosPackage rec {
  pname = "ros-jazzy-perseus-payloads-py";
  version = "0.0.0";

  src = ./../src/perseus_payloads_py;

  buildType = "ament_python";
  checkInputs = [
    ament-copyright
    ament-flake8
    ament-pep257
    python3Packages.pytest
  ];
  propagatedBuildInputs = [
    actuator-msgs
    perseus-interfaces
    python3Packages.pyserial
    rclpy
    sensor-msgs
    std-msgs
  ];

  meta = {
    description = "TODO: Package description";
    license = with lib.licenses; [ "TODO-License-declaration" ];
  };
}
