# Automatically generated by: ros2nix --output-dir=ros_ws/nix-packages --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-cmake,
  fast-lio,
}:
buildRosPackage rec {
  pname = "ros-jazzy-perseus-mapping";
  version = "0.0.1";

  src = ./../src/perseus_mapping;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  propagatedBuildInputs = [ fast-lio ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "Config files for Perseus 3D mapping nodes and launch files";
    license = with lib.licenses; [ mit ];
  };
}
