# Automatically generated by: ros2nix --output-dir=ros_ws/nix-packages --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-cmake,
  hardware-interface,
  joint-state-publisher,
  pluginlib,
  rclcpp,
  rclcpp-lifecycle,
  robot-state-publisher,
  rviz2,
  serial,
  urdf,
  xacro,
}:
buildRosPackage rec {
  pname = "ros-jazzy-perseus-lite-description";
  version = "0.1.0";

  src = ./../src/perseus_lite_hardware;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  propagatedBuildInputs = [
    hardware-interface
    joint-state-publisher
    pluginlib
    rclcpp
    rclcpp-lifecycle
    robot-state-publisher
    rviz2
    serial
    urdf
    xacro
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "URDF description and hardware interface for Perseus Lite robot";
    license = with lib.licenses; [ "TODO-CATKIN-PACKAGE-LICENSE" ];
  };
}
