# Automatically generated by: ros2nix --output-dir=ros_ws/nix-packages --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-cmake,
  hi-can-raw,
  nav-msgs,
  rclcpp,
  sensor-msgs,
  std-msgs,
}:
buildRosPackage rec {
  pname = "ros-jazzy-perseus-lights";
  version = "0.0.0";

  src = ./../src/perseus_lights;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  propagatedBuildInputs = [
    hi-can-raw
    nav-msgs
    rclcpp
    sensor-msgs
    std-msgs
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "Control the light ring via CAN. This is the driver allowing other nodes to control the lights with a /status topic";
    license = with lib.licenses; [ mit ];
  };
}
