# Automatically generated by: ros2nix --output-dir=ros_ws/nix-packages --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-cmake,
  hardware-interface,
  pluginlib,
  rclcpp,
  rclcpp-lifecycle,
  serial,
}:
buildRosPackage rec {
  pname = "ros-jazzy-perseus-lite-hardware";
  version = "0.1.0";

  src = ./../src/perseus_lite_hardware;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  propagatedBuildInputs = [
    hardware-interface
    pluginlib
    rclcpp
    rclcpp-lifecycle
    serial
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "Hardware interface for Perseus Lite robot";
    license = with lib.licenses; [ "TODO-CATKIN-PACKAGE-LICENSE" ];
  };
}
