# Automatically generated by: ros2nix --output-dir=ros_ws/nix-packages --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-cmake,
  ament-lint-auto,
  ament-lint-common,
  domain-bridge,
}:
buildRosPackage rec {
  pname = "ros-jazzy-perseus-domain-bridge";
  version = "0.0.0";

  src = ./../src/perseus_domain_bridge;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  checkInputs = [
    ament-lint-auto
    ament-lint-common
  ];
  propagatedBuildInputs = [ domain-bridge ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "Configuration and launch files for ROS2 domain bridge";
    license = with lib.licenses; [ mit ];
  };
}
