# Automatically generated by: ros2nix --output-dir=ros_ws/nix-packages --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  action-msgs,
  ament-flake8,
  ament-pep257,
  autonomy,
  geometry-msgs,
  launch,
  launch-ros,
  nav2-msgs,
  perseus-lite-simulation,
  python3Packages,
  rclpy,
  ros-gz-bridge,
  slam-toolbox,
  std-msgs,
  tf2-ros,
}:
buildRosPackage rec {
  pname = "ros-jazzy-perseus-lite-missions";
  version = "0.1.0";

  src = ./../src/perseus_lite_missions;

  buildType = "ament_python";
  checkInputs = [
    ament-flake8
    ament-pep257
    python3Packages.pytest
  ];
  propagatedBuildInputs = [
    action-msgs
    autonomy
    geometry-msgs
    launch
    launch-ros
    nav2-msgs
    perseus-lite-simulation
    rclpy
    ros-gz-bridge
    slam-toolbox
    std-msgs
    tf2-ros
  ];

  meta = {
    description = "Mission Zero (Selene Base Rescue) and follow-on scripted missions for the lite robot tutorial campaign.";
    license = with lib.licenses; [ mit ];
  };
}
