# Automatically generated by: ros2nix --output-dir=ros_ws/nix-packages --output-as-nix-pkg-name --no-default --distro humble
{
  lib,
  buildRosPackage,
  ament-cmake,
  controller-manager,
  diff-drive-controller,
  joint-state-broadcaster,
  perseus-hardware,
  robot-state-publisher,
  ros2controlcli,
  ros2launch,
  rviz2,
  xacro,
}:
buildRosPackage rec {
  pname = "ros-humble-perseus";
  version = "0.0.0";

  src = ./../src/perseus;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  propagatedBuildInputs = [
    controller-manager
    diff-drive-controller
    joint-state-broadcaster
    perseus-hardware
    robot-state-publisher
    ros2controlcli
    ros2launch
    rviz2
    xacro
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "Perseus V2 Rover Bringup";
    license = with lib.licenses; [ mit ];
  };
}
