# Automatically generated by: ros2nix --output-dir=ros_ws/nix-packages --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  geometry-msgs,
  rclpy,
}:
buildRosPackage rec {
  pname = "ros-jazzy-perseus-teleop";
  version = "2.3.3";

  src = ./../src/perseus_teleop;

  buildType = "ament_python";
  propagatedBuildInputs = [
    geometry-msgs
    rclpy
  ];

  meta = {
    description = "Teleoperation node using keyboard for Perseus.";
    license = with lib.licenses; [ asl20 ];
  };
}
