# Automatically generated by: ros2nix --output-dir=ros_ws/nix-packages --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  actuator-msgs,
  ament-cmake,
  backward-ros,
  geometry-msgs,
  rclcpp,
  sensor-msgs,
}:
buildRosPackage rec {
  pname = "ros-jazzy-perseus-system-status";
  version = "0.0.1";

  src = ./../src/perseus_system_status;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  propagatedBuildInputs = [
    actuator-msgs
    backward-ros
    geometry-msgs
    rclcpp
    sensor-msgs
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "Nodes for handling system status information in perseus";
    license = with lib.licenses; [ mit ];
  };
}
