# Automatically generated by: ros2nix --output-dir=ros_ws/nix-packages --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-cmake,
  joint-state-publisher-gui,
  robot-state-publisher,
  rviz2,
}:
buildRosPackage rec {
  pname = "ros-jazzy-perseus-description";
  version = "0.0.1";

  src = ./../src/perseus_description;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  propagatedBuildInputs = [
    joint-state-publisher-gui
    robot-state-publisher
    rviz2
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "Package containing description files for Perseus V2";
    license = with lib.licenses; [ mit ];
  };
}
