# Automatically generated by: ros2nix --output-dir=ros_ws/nix-packages --output-as-nix-pkg-name --no-default --distro jazzy
{ lib, buildRosPackage, action-msgs, ament-cmake, builtin-interfaces, rosidl-default-generators, std-msgs }:
buildRosPackage rec {
  pname = "ros-jazzy-perseus-msgs";
  version = "0.0.0";

  src = ./../src/perseus_msgs;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  propagatedBuildInputs = [ action-msgs builtin-interfaces rosidl-default-generators std-msgs ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "This package has all custom msg interfaces for the perseus platform. This can include msgs, srvs and actions.";
    license = with lib.licenses; [ "TODO-License-declaration" ];
  };
}
