# Automatically generated by: ros2nix --output-dir=ros_ws/nix-packages --output-as-nix-pkg-name --no-default --distro jazzy
{ lib, buildRosPackage, ament-cmake, ament-index-cpp, ament-lint-auto, ament-lint-common, geometry-msgs, launch-ros, nav-msgs, nav2-behavior-tree, nav2-common, nav2-core, nav2-msgs, nav2-util, navigation2, pluginlib, rclcpp, rclcpp-action, rclcpp-components, rclcpp-lifecycle, ros2launch, rviz2, slam-toolbox, tf2-ros }:
buildRosPackage rec {
  pname = "ros-jazzy-perseus-navigator";
  version = "0.0.0";

  src = ./../src/perseus_navigator;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  checkInputs = [ ament-lint-auto ament-lint-common ];
  propagatedBuildInputs = [ ament-index-cpp geometry-msgs launch-ros nav-msgs nav2-behavior-tree nav2-common nav2-core nav2-msgs nav2-util navigation2 pluginlib rclcpp rclcpp-action rclcpp-components rclcpp-lifecycle ros2launch rviz2 slam-toolbox tf2-ros ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "TODO: Package description";
    license = with lib.licenses; [ "TODO-License-declaration" ];
  };
}
