# Automatically generated by: ros2nix --output-dir=ros_ws/nix-packages --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-cmake,
  ament-lint-auto,
  ament-lint-common,
  cv-bridge,
  geometry-msgs,
  image-transport,
  onnxruntime,
  opencv,
  rclcpp,
  rosidl-default-generators,
  sensor-msgs,
  tf2,
  tf2-ros,
  tf2-geometry-msgs,
}:
buildRosPackage rec {
  pname = "ros-jazzy-perseus-vision";
  version = "0.0.0";

  src = ./../src/perseus_vision;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake rosidl-default-generators ];
  checkInputs = [
    ament-lint-auto
    ament-lint-common
  ];
  propagatedBuildInputs = [
    cv-bridge
    geometry-msgs
    image-transport
    onnxruntime
    opencv
    rclcpp
    sensor-msgs
    tf2
    tf2-ros
    tf2-geometry-msgs
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "A package to do visionary tasks of Perseus";
    license = with lib.licenses; [ mit ];
  };
}
