# Automatically generated by: ros2nix --output-dir=ros_ws/nix-packages --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-cmake,
  backward-ros,
  rclcpp,
  sensor-msgs,
}:
buildRosPackage rec {
  pname = "ros-jazzy-perseus-sensors";
  version = "0.0.0";

  src = ./../src/perseus_sensors;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  propagatedBuildInputs = [
    backward-ros
    rclcpp
    sensor-msgs
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "TODO: Package description";
    license = with lib.licenses; [ mit ];
  };
}
