# Automatically generated by: ros2nix --output-dir=ros_ws/nix-packages --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-cmake,
  control-msgs,
  cv-bridge,
  geometry-msgs,
  image-transport,
  nav-msgs,
  perseus-interfaces,
  rclcpp,
  sensor-msgs,
  std-msgs,
  tf2-geometry-msgs,
  tf2-ros,
}:
buildRosPackage rec {
  pname = "ros-jazzy-perseus-lite-hud";
  version = "0.1.0";

  src = ./../src/perseus_lite_hud;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  propagatedBuildInputs = [
    control-msgs
    cv-bridge
    geometry-msgs
    image-transport
    nav-msgs
    perseus-interfaces
    rclcpp
    sensor-msgs
    std-msgs
    tf2-geometry-msgs
    tf2-ros
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "Camera HUD overlay for Perseus Lite";
    license = with lib.licenses; [ mit ];
  };
}
