# Automatically generated by: ros2nix --output-dir=ros_ws/nix-packages --output-as-nix-pkg-name --no-default --distro jazzy
#
# NOTE: hand-edited to add message-filters/image-transport/nav-msgs/std-srvs after the
# stereo_odometry node was added, without re-running ros2nix (see
# software/scripts/nix-package.sh, which also needs network access and auto-commits).
# Re-run that script to regenerate this file properly and verify these attribute names.
{
  lib,
  buildRosPackage,
  ament-cmake,
  ament-index-cpp,
  ament-lint-auto,
  ament-lint-common,
  builtin-interfaces,
  cv-bridge,
  geometry-msgs,
  image-transport,
  message-filters,
  nav-msgs,
  onnxruntime,
  opencv,
  perseus-interfaces,
  rcl-interfaces,
  rclcpp,
  rclcpp-components,
  sensor-msgs,
  std-msgs,
  std-srvs,
  tf2,
  tf2-geometry-msgs,
  tf2-ros,
  v4l2-camera,
  visualization-msgs,
}:
buildRosPackage rec {
  pname = "ros-jazzy-perseus-vision";
  version = "1.0.0";

  src = ./../src/perseus_vision;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  checkInputs = [
    ament-lint-auto
    ament-lint-common
  ];
  propagatedBuildInputs = [
    ament-index-cpp
    builtin-interfaces
    cv-bridge
    geometry-msgs
    image-transport
    message-filters
    nav-msgs
    onnxruntime
    opencv
    perseus-interfaces
    rcl-interfaces
    rclcpp
    rclcpp-components
    sensor-msgs
    std-msgs
    std-srvs
    tf2
    tf2-geometry-msgs
    tf2-ros
    v4l2-camera
    visualization-msgs
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "A package to do vision/detection tasks of Perseus";
    license = with lib.licenses; [ mit ];
  };
}
