# Automatically generated by: ros2nix --output-dir=ros_ws/nix-packages --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-copyright,
  ament-flake8,
  ament-pep257,
  nav-msgs,
  python3Packages,
  rclpy,
}:
buildRosPackage rec {
  pname = "ros-jazzy-perseus-lite-drifting";
  version = "0.1.0";

  src = ./../src/perseus_lite_drifting;

  buildType = "ament_python";
  checkInputs = [
    ament-copyright
    ament-flake8
    ament-pep257
    python3Packages.pytest
  ];
  propagatedBuildInputs = [
    nav-msgs
    rclpy
  ];

  meta = {
    description = "Plays a drift sound effect when Perseus Lite is drifting (simultaneous linear and angular motion)";
    license = with lib.licenses; [ mit ];
  };
}
