# Automatically generated by: ros2nix --fetch --output-dir=out --output-as-nix-pkg-name --distro jazzy
{
  lib,
  buildRosPackage,
  fetchFromGitHub,
  ament-cmake,
  ament-lint-common,
  geometry-msgs,
  rosidl-default-generators,
  rosidl-default-runtime,
  sensor-msgs,
  std-msgs,
}:
buildRosPackage rec {
  pname = "ros-jazzy-mesh-msgs";
  version = "2.1.1";

  src = fetchFromGitHub {
    owner = "naturerobots";
    repo = "mesh_tools";
    rev = "f79a742d61382299370402d8c0460685d1c2e8c0";
    sha256 = "1kjf2rrs3slmanywv3rmxh0idpbyz3s66lhzzwzk3snf1a429ibd";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/mesh_msgs/";
  buildInputs = [
    ament-cmake
    rosidl-default-generators
  ];
  checkInputs = [ ament-lint-common ];
  propagatedBuildInputs = [
    geometry-msgs
    rosidl-default-runtime
    sensor-msgs
    std-msgs
  ];
  nativeBuildInputs = [
    ament-cmake
    rosidl-default-generators
  ];

  meta = {
    description = "Various Message Types for Mesh Data.";
    license = with lib.licenses; [ bsd3 ];
  };
}
