# Automatically generated by: ros2nix --fetch --output-dir=out --output-as-nix-pkg-name --distro jazzy
{
  lib,
  buildRosPackage,
  fetchFromGitHub,
  ament-cmake,
  ament-lint-auto,
  ament-lint-common,
  lvr2,
  mesh-msgs,
  rclcpp,
  sensor-msgs,
  # Not in package.xml, so ros2nix didn't pick these up -- CMakeLists.txt find_package()s
  # both directly (REQUIRED), copy-pasted from lvr2's own list and unused by the actual
  # conversions code. Passed in from ../overlay.nix since neither is in the ROS package set.
  pkg-config,
  mpi,
}:
buildRosPackage rec {
  pname = "ros-jazzy-mesh-msgs-conversions";
  version = "2.1.1";

  src = fetchFromGitHub {
    owner = "naturerobots";
    repo = "mesh_tools";
    rev = "f79a742d61382299370402d8c0460685d1c2e8c0";
    sha256 = "1kjf2rrs3slmanywv3rmxh0idpbyz3s66lhzzwzk3snf1a429ibd";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/mesh_msgs_conversions/";
  buildInputs = [
    ament-cmake
    mpi
  ];
  checkInputs = [
    ament-lint-auto
    ament-lint-common
  ];
  propagatedBuildInputs = [
    lvr2
    mesh-msgs
    rclcpp
    sensor-msgs
  ];
  nativeBuildInputs = [
    ament-cmake
    pkg-config
  ];

  meta = {
    description = "converts point clouds and attributes into meshes and mesh attributes";
    license = with lib.licenses; [ bsd3 ];
  };
}
