#include "quadrature_encoders.hpp"
#include "quadrature_encoder.pio.h"  // generated by CMake from .pio file

void QuadratureEncoders::init() {
    // Load the PIO program once — both state machines share the same
    // loaded program. The program MUST sit at offset 0 (jump table relies
    // on absolute addresses), so we assert that here.
    pio_program_offset_ = pio_add_program(ENC_PIO, &quadrature_encoder_program);

    // Encoder A: GP13 (A), GP14 (B)
    quadrature_encoder_program_init(
        ENC_PIO, ENC_A_SM, pio_program_offset_,
        ENC_A_PIN_A,
        0  // max_step_rate = 0 → full speed
    );

    // Encoder B: GP15 (A), GP16 (B)
    quadrature_encoder_program_init(
        ENC_PIO, ENC_B_SM, pio_program_offset_,
        ENC_B_PIN_A,
        0  // max_step_rate = 0 → full speed
    );

    initialised_ = true;
}

int32_t QuadratureEncoders::getCountA() const {
    return quadrature_encoder_get_count(ENC_PIO, ENC_A_SM);
}

int32_t QuadratureEncoders::getCountB() const {
    return quadrature_encoder_get_count(ENC_PIO, ENC_B_SM);
}

void QuadratureEncoders::resetCounts() {
    // Reinitialise both SMs — the PIO X register is reset to 0 on SM init.
    // The program is already loaded so we just re-run the init helper.
    quadrature_encoder_program_init(
        ENC_PIO, ENC_A_SM, pio_program_offset_, ENC_A_PIN_A, 0);
    quadrature_encoder_program_init(
        ENC_PIO, ENC_B_SM, pio_program_offset_, ENC_B_PIN_A, 0);
}
