slam_toolbox:
  ros__parameters:
    # Plugin params
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None
    # ROS Parameters
    #odom_frame: odom
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    use_map_saver: true
    mode: mapping
    # Sync mapping configuration
    sync_mapping: true
    # lifelong params
    lifelong_search_use_tree: false
    lifelong_minimum_score: 0.1
    lifelong_iou_match: 0.85
    lifelong_node_removal_score: 0.04
    lifelong_overlap_score_scale: 0.06
    lifelong_constraint_multiplier: 0.08
    lifelong_nearby_penalty: 0.001
    lifelong_candidates_scale: 0.03
    # if you'd like to immediately start continuing a map at a given pose
    # or at the dock, but they are mutually exclusive, if pose is given
    # will use pose
    #map_file_name: test_steve
    #map_start_pose: [0.0, 0.0, 0.0]
    #map_start_at_dock: true
    debug_logging: false
    throttle_scans: 1
    transform_publish_period: 0.0 #if 0 never publishes odometry
    # Multi-threading parameters
    enable_interactive_mode: true
    publish_period: 0.1
    map_update_interval: 0.3
    resolution: 0.02
    max_laser_range: 8.0 #for rastering images - reduced for indoor
    minimum_time_interval: 0.3 #faster updates for indoor mapping
    transform_timeout: 0.2
    tf_buffer_duration: 2.
    stack_size_to_use: 40000000 #// program needs a larger stack size to serialize large maps
    # General Parameters
    use_scan_matching: true
    use_scan_barycenter: true
    use_imu: true
    minimum_travel_distance: 0.1
    minimum_travel_heading: 0.2
    scan_buffer_size: 20
    scan_buffer_maximum_scan_distance: 5.0
    link_match_minimum_response_fine: 0.2
    link_scan_maximum_distance: 1.0
    loop_search_maximum_distance: 2.0
    do_loop_closing: true
    loop_match_minimum_chain_size: 5
    loop_match_maximum_variance_coarse: 2.0
    loop_match_minimum_response_coarse: 0.25
    loop_match_minimum_response_fine: 0.35
    # Correlation Parameters - Correlation Parameters
    correlation_search_space_dimension: 0.3
    correlation_search_space_resolution: 0.005
    correlation_search_space_smear_deviation: 0.05
    # Correlation Parameters - Loop Closure Parameters
    loop_search_space_dimension: 4.0
    loop_search_space_resolution: 0.03
    loop_search_space_smear_deviation: 0.02
    # Scan Matcher Parameters
    distance_variance_penalty: 0.3
    angle_variance_penalty: 0.7
    fine_search_angle_offset: 0.00349
    coarse_search_angle_offset: 0.262
    coarse_angle_resolution: 0.0262
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true
