/**:
  ros__parameters:
    feature_extract_enable: true
    point_filter_num: 1
    max_iteration: 30
    filter_size_surf: 0.1
    filter_size_map: 0.2
    cube_side_length: 1000.0
    runtime_pos_log_enable: false
    map_file_path: "~/maps/scan.pcd"
    common:
      lid_topic: "/livox/lidar_filtered" # simulation - filtered to remove NaN/Inf values
      # lid_topic: "/livox/lidar" # physical rover
      imu_topic: "/livox/imu"
      map_frame: "lidar_map"
      body_frame: "lidar_odom"
      lid_frame: "livox_frame"
      time_sync_en: false
      time_offset_lidar_to_imu: 0.0
    preprocess:
      lidar_type: 4
      scan_line: 32
      blind: 0.1
      timestamp_unit: 3
      scan_rate: 10
    mapping:
      acc_cov: 0.001
      gyr_cov: 0.001
      b_acc_cov: 0.000001
      b_gyr_cov: 0.000001
      fov_degree: 360.0
      det_range: 30.0
      extrinsic_est_en: false
      extrinsic_T: [0.011, 0.02329, -0.04412]
      extrinsic_R: [1., 0., 0., 0., 1., 0., 0., 0., 1.]
    publish:
      path_en: true
      effect_map_en: true
      map_en: true
      scan_publish_en: true
      dense_publish_en: false
      scan_bodyframe_pub_en: true
    pcd_save:
      pcd_save_en: true
      interval: -1
