# Automatically generated by: ros2nix --fetch --output-dir=out --output-as-nix-pkg-name --distro jazzy
{
  lib,
  buildRosPackage,
  fetchFromGitHub,
  geometry-msgs,
  mbf-abstract-core,
  mbf-abstract-nav,
  mbf-mesh-core,
  mbf-msgs,
  mbf-simple-core,
  mbf-simple-nav,
  mesh-map,
  nav-msgs,
  pluginlib,
  rclcpp,
  std-srvs,
}:
buildRosPackage rec {
  pname = "ros-jazzy-mbf-mesh-nav";
  version = "3.0.1";

  src = fetchFromGitHub {
    owner = "bocho0600";
    repo = "mesh_navigation";
    rev = "aee7b513a9b6b44239c4cfc8bc6bd418ecb81656";
    sha256 = "1n3708k7fpami2p4lcabpm1bgpxx1a27rpqincrxxqy0j61w04fb";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/mbf_mesh_nav/";
  propagatedBuildInputs = [
    geometry-msgs
    mbf-abstract-core
    mbf-abstract-nav
    mbf-mesh-core
    mbf-msgs
    mbf-simple-core
    mbf-simple-nav
    mesh-map
    nav-msgs
    pluginlib
    rclcpp
    std-srvs
  ];

  meta = {
    description = "The mbf_mesh_nav package";
    license = with lib.licenses; [ bsd3 ];
  };
}
