# Automatically generated by: ros2nix --fetch --output-dir=out --output-as-nix-pkg-name --distro jazzy
{
  lib,
  buildRosPackage,
  fetchFromGitHub,
  mbf-abstract-core,
  mesh-map,
}:
buildRosPackage rec {
  pname = "ros-jazzy-mbf-mesh-core";
  version = "3.0.1";

  src = fetchFromGitHub {
    owner = "bocho0600";
    repo = "mesh_navigation";
    rev = "aee7b513a9b6b44239c4cfc8bc6bd418ecb81656";
    sha256 = "1n3708k7fpami2p4lcabpm1bgpxx1a27rpqincrxxqy0j61w04fb";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/mbf_mesh_core/";
  propagatedBuildInputs = [
    mbf-abstract-core
    mesh-map
  ];

  meta = {
    description = "The mbf_mesh_core package";
    license = with lib.licenses; [ bsd3 ];
  };
}
