# Automatically generated by: ros2nix --fetch --output-dir=out --output-as-nix-pkg-name --distro jazzy
{
  lib,
  buildRosPackage,
  fetchFromGitHub,
  example-interfaces,
  mbf-mesh-core,
  mbf-msgs,
  mbf-utility,
  mesh-map,
  rclcpp,
  tf2-geometry-msgs,
}:
buildRosPackage rec {
  pname = "ros-jazzy-mesh-controller";
  version = "3.0.1";

  src = fetchFromGitHub {
    owner = "bocho0600";
    repo = "mesh_navigation";
    rev = "aee7b513a9b6b44239c4cfc8bc6bd418ecb81656";
    sha256 = "1n3708k7fpami2p4lcabpm1bgpxx1a27rpqincrxxqy0j61w04fb";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/mesh_controller/";
  propagatedBuildInputs = [
    example-interfaces
    mbf-mesh-core
    mbf-msgs
    mbf-utility
    mesh-map
    rclcpp
    tf2-geometry-msgs
  ];

  meta = {
    description = "The mesh_controller package";
    license = with lib.licenses; [ bsd3 ];
  };
}
