# Automatically generated by: ros2nix --fetch --output-dir=out --output-as-nix-pkg-name --distro jazzy
{
  lib,
  buildRosPackage,
  fetchFromGitHub,
  lvr2,
  mesh-map,
}:
buildRosPackage rec {
  pname = "ros-jazzy-mesh-layers";
  version = "3.0.1";

  src = fetchFromGitHub {
    owner = "bocho0600";
    repo = "mesh_navigation";
    rev = "aee7b513a9b6b44239c4cfc8bc6bd418ecb81656";
    sha256 = "1n3708k7fpami2p4lcabpm1bgpxx1a27rpqincrxxqy0j61w04fb";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/mesh_layers/";
  propagatedBuildInputs = [
    lvr2
    mesh-map
  ];

  meta = {
    description = "The mesh_layers package";
    license = with lib.licenses; [ bsd3 ];
  };
}
