# Automatically generated by: ros2nix --fetch --output-dir=out --output-as-nix-pkg-name --distro jazzy
{
  lib,
  buildRosPackage,
  fetchFromGitHub,
  ament-cmake-gtest,
  assimp,
  geometry-msgs,
  mesh-msgs-conversions,
  pluginlib,
  rclcpp,
  std-srvs,
  tf2,
  tf2-geometry-msgs,
  tf2-ros,
  visualization-msgs,
}:
buildRosPackage rec {
  pname = "ros-jazzy-mesh-map";
  version = "3.0.1";

  src = fetchFromGitHub {
    owner = "bocho0600";
    repo = "mesh_navigation";
    rev = "aee7b513a9b6b44239c4cfc8bc6bd418ecb81656";
    sha256 = "1n3708k7fpami2p4lcabpm1bgpxx1a27rpqincrxxqy0j61w04fb";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/mesh_map/";
  # Adds a mesh_geometry_sub (mesh_msgs/MeshGeometryStamped, on ~/mesh_update) that
  # replaces the loaded mesh and reruns readMap() -- see the patch for why, and
  # patches/mesh-map-streamed-reload.patch itself for the exact reload path.
  patches = [ ./patches/mesh-map-streamed-reload.patch ];
  checkInputs = [ ament-cmake-gtest ];
  propagatedBuildInputs = [
    assimp
    geometry-msgs
    mesh-msgs-conversions
    pluginlib
    rclcpp
    std-srvs
    tf2
    tf2-geometry-msgs
    tf2-ros
    visualization-msgs
  ];

  meta = {
    description = "The mesh_map package";
    license = with lib.licenses; [ bsd3 ];
  };
}
