# Automatically generated by: ros2nix --fetch --output-dir=out --output-as-nix-pkg-name --distro jazzy
{
  lib,
  buildRosPackage,
  fetchFromGitHub,
  cvp-mesh-planner,
  dijkstra-mesh-planner,
  mbf-mesh-core,
  mbf-mesh-nav,
  mesh-controller,
  mesh-layers,
  mesh-map,
}:
buildRosPackage rec {
  pname = "ros-jazzy-mesh-navigation";
  version = "3.0.1";

  src = fetchFromGitHub {
    owner = "bocho0600";
    repo = "mesh_navigation";
    rev = "aee7b513a9b6b44239c4cfc8bc6bd418ecb81656";
    sha256 = "1n3708k7fpami2p4lcabpm1bgpxx1a27rpqincrxxqy0j61w04fb";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/mesh_navigation/";
  propagatedBuildInputs = [
    cvp-mesh-planner
    dijkstra-mesh-planner
    mbf-mesh-core
    mbf-mesh-nav
    mesh-controller
    mesh-layers
    mesh-map
  ];

  meta = {
    description = "The mesh_navigation package provides a layered mesh_map implementation, a Move Base Flex mesh navigation server, as well as mesh navigation plugins for path planning and navigation control.";
    license = with lib.licenses; [ bsd3 ];
  };
}
