#include "quadrature_encoders.hpp"


#include "quadrature_encoder.pio.h"  // generated by CMake from .pio file

void QuadratureEncoders::init()
{
    gpio_pull_up(kEncAPinA);
    gpio_pull_up(kEncAPinB);
    gpio_pull_up(kEncBPinA);
    gpio_pull_up(kEncBPinB);

    pio_program_offset_ = pio_add_program(pio0, &quadrature_encoder_program);

    quadrature_encoder_program_init(pio0, kEncASm, pio_program_offset_, kEncAPinA, 0);
    quadrature_encoder_program_init(pio0, kEncBSm, pio_program_offset_, kEncBPinA, 0);

    initialised_ = true;
}

int32_t QuadratureEncoders::getCountA() const
{
    pio_sm_exec(pio0, kEncASm, pio_encode_in(pio_x, 32));
    int32_t count = 0;
    while (!pio_sm_is_rx_fifo_empty(pio0, kEncASm))
        count = static_cast<int32_t>(pio_sm_get(pio0, kEncASm));
    return count;
}

int32_t QuadratureEncoders::getCountB() const
{
    pio_sm_exec(pio0, kEncBSm, pio_encode_in(pio_x, 32));
    int32_t count = 0;
    while (!pio_sm_is_rx_fifo_empty(pio0, kEncBSm))
        count = static_cast<int32_t>(pio_sm_get(pio0, kEncBSm));
    return count;
}

void QuadratureEncoders::resetCounts()
{
    quadrature_encoder_program_init(pio0, kEncASm, pio_program_offset_, kEncAPinA, 0);
    quadrature_encoder_program_init(pio0, kEncBSm, pio_program_offset_, kEncBPinA, 0);
}