#include "quadrature_encoders.hpp"

#include "quadrature_encoder.pio.h"  // generated by CMake from .pio file

void QuadratureEncoders::init()
{
    // Configure encoder pins as inputs with pull-ups
    gpio_pull_up(ENC_A_PIN_A);
    gpio_pull_up(ENC_A_PIN_B);
    gpio_pull_up(ENC_B_PIN_A);
    gpio_pull_up(ENC_B_PIN_B);

    pio_program_offset_ = pio_add_program(ENC_PIO, &quadrature_encoder_program);

    // Encoder A: GP13 (A), GP14 (B)
    quadrature_encoder_program_init(
        ENC_PIO, ENC_A_SM, pio_program_offset_,
        ENC_A_PIN_A,
        0  // max_step_rate = 0 \u2192 full speed
    );

    // Encoder B: GP15 (A), GP16 (B)
    quadrature_encoder_program_init(
        ENC_PIO, ENC_B_SM, pio_program_offset_,
        ENC_B_PIN_A,
        0  // max_step_rate = 0 \u2192 full speed
    );

    initialised_ = true;
}

int32_t QuadratureEncoders::getCountA() const
{
    // Force push X into FIFO non-blocking
    pio_sm_exec(ENC_PIO, ENC_A_SM, pio_encode_in(pio_x, 32));
    // Drain old values, take the latest
    int32_t count = 0;
    while (!pio_sm_is_rx_fifo_empty(ENC_PIO, ENC_A_SM))
        count = (int32_t)pio_sm_get(ENC_PIO, ENC_A_SM);
    return count;
}

int32_t QuadratureEncoders::getCountB() const
{
    pio_sm_exec(ENC_PIO, ENC_B_SM, pio_encode_in(pio_x, 32));
    int32_t count = 0;
    while (!pio_sm_is_rx_fifo_empty(ENC_PIO, ENC_B_SM))
        count = (int32_t)pio_sm_get(ENC_PIO, ENC_B_SM);
    return count;
}

void QuadratureEncoders::resetCounts()
{
    // Reinitialise both SMs \u2014 the PIO X register is reset to 0 on SM init.
    // The program is already loaded so we just re-run the init helper.
    quadrature_encoder_program_init(
        ENC_PIO, ENC_A_SM, pio_program_offset_, ENC_A_PIN_A, 0);
    quadrature_encoder_program_init(
        ENC_PIO, ENC_B_SM, pio_program_offset_, ENC_B_PIN_A, 0);
}
