# Automatically generated by: ros2nix --fetch --distro jazzy
{
  lib,
  buildRosPackage,
  fetchFromGitHub,
  ament-cmake,
  pcl,
  rclcpp,
  std-msgs,
}:
buildRosPackage rec {
  pname = "ros-jazzy-ndt-omp-ros2";
  version = "0.0.0";

  src = fetchFromGitHub {
    owner = "rsasaki0109";
    repo = "ndt_omp_ros2";
    rev = "41bdfba539bb4fe8becd4bc6cf9cd5e5ad35dab1";
    sha256 = "0rrw7d314x3mpwsi8mq0ga1kxr2pjkqlpc3jpsrwk98h43pshz1k";
  };

  buildType = "ament_cmake";
  buildInputs = [
    ament-cmake
    pcl
    rclcpp
    std-msgs
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "OpenMP boosted NDT and GICP algorithms";
    license = with lib.licenses; [ bsdOriginal ];
  };
}
