# Automatically generated by: ros2nix --fetch --distro jazzy --output-as-ros-pkg-name
{ lib, buildRosPackage, fetchFromGitHub, ament-cmake, ament-lint-auto, ament-lint-common, graph-based-slam, lidarslam-msgs, nav-msgs, pcl-conversions, rclcpp, scanmatcher, std-srvs, tf2-eigen, tf2-geometry-msgs, tf2-ros }:
buildRosPackage rec {
  pname = "ros-jazzy-lidarslam";
  version = "0.0.0";

  src = fetchFromGitHub {
    owner = "rsasaki0109";
    repo = "lidarslam_ros2";
    rev = "ed18ccb6f2a22c4baeaf336b39aeb65a88ee8715";
    sha256 = "0yd4djzny69plp2rv98zjm9r8kvzl6285n11sfhkrkfdn2nrg9f0";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/lidarslam/";
  buildInputs = [ ament-cmake ];
  checkInputs = [ ament-lint-auto ament-lint-common ];
  propagatedBuildInputs = [ graph-based-slam lidarslam-msgs nav-msgs pcl-conversions rclcpp scanmatcher std-srvs tf2-eigen tf2-geometry-msgs tf2-ros ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "lidarslam_ros2 integration package";
    license = with lib.licenses; [ "BSD-2-Clause" ];
  };
}
