# Automatically generated by: ros2nix --fetch --distro jazzy --output-as-ros-pkg-name
{
  lib,
  buildRosPackage,
  fetchFromGitHub,
  ament-cmake,
  ament-lint-auto,
  ament-lint-common,
  geometry-msgs,
  rosidl-default-generators,
  rosidl-default-runtime,
  sensor-msgs,
  std-msgs,
}:
buildRosPackage rec {
  pname = "ros-jazzy-lidarslam-msgs";
  version = "0.0.0";

  src = fetchFromGitHub {
    owner = "rsasaki0109";
    repo = "lidarslam_ros2";
    rev = "ed18ccb6f2a22c4baeaf336b39aeb65a88ee8715";
    sha256 = "0yd4djzny69plp2rv98zjm9r8kvzl6285n11sfhkrkfdn2nrg9f0";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/lidarslam_msgs/";
  buildInputs = [
    ament-cmake
    rosidl-default-generators
  ];
  checkInputs = [
    ament-lint-auto
    ament-lint-common
  ];
  propagatedBuildInputs = [
    geometry-msgs
    rosidl-default-runtime
    sensor-msgs
    std-msgs
  ];
  nativeBuildInputs = [
    ament-cmake
    rosidl-default-generators
  ];

  meta = {
    description = "lidarslam_ros2 msgs";
    license = with lib.licenses; [ "BSD-2-Clause" ];
  };
}
