# Automatically generated by: ros2nix --fetch --distro jazzy --output-as-ros-pkg-name
{
  lib,
  buildRosPackage,
  fetchFromGitHub,
  ament-cmake,
  ament-lint-auto,
  ament-lint-common,
  geometry-msgs,
  libg2o,
  lidarslam-msgs,
  nav-msgs,
  ndt-omp-ros2,
  pcl,
  pcl-conversions,
  rclcpp,
  rclcpp-components,
  sensor-msgs,
  tf2-eigen,
  tf2-geometry-msgs,
  tf2-ros,
  tf2-sensor-msgs,
}:
buildRosPackage rec {
  pname = "ros-jazzy-scanmatcher";
  version = "0.0.0";

  src = fetchFromGitHub {
    owner = "rsasaki0109";
    repo = "lidarslam_ros2";
    rev = "ed18ccb6f2a22c4baeaf336b39aeb65a88ee8715";
    sha256 = "0yd4djzny69plp2rv98zjm9r8kvzl6285n11sfhkrkfdn2nrg9f0";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/scanmatcher/";
  buildInputs = [ ament-cmake ];
  propagatedBuildInputs = [
    ament-lint-auto
    ament-lint-common
    geometry-msgs
    libg2o
    lidarslam-msgs
    nav-msgs
    ndt-omp-ros2
    pcl
    pcl-conversions
    rclcpp
    rclcpp-components
    sensor-msgs
    tf2-eigen
    tf2-geometry-msgs
    tf2-ros
    tf2-sensor-msgs
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "scan-matching package";
    license = with lib.licenses; [ "BSD-2-Clause" ];
  };
}
