<?xml version="1.0"?>
<robot name="chassis" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:property name="chassis_mass" value="2.7689940302592726"/>  <!-- Kg -->

  <link name="${prefix}chassis">
    <inertial>
      <origin xyz="${-chassis_length*0.5} 0.0 ${chassis_height*0.5}" rpy="0 0.0 0.0"/>
      <mass value="${chassis_mass}"/>
      <xacro:box_inertia m="${chassis_mass}" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}"/>
    </inertial>
    <visual>
      <origin xyz="0.0 0.0 0.0" rpy="0 0.0 -${pi/2}"/>
      <geometry>
        <mesh scale="0.1 0.1  0.1" filename="file://$(find perseus_description)/meshes/chassis.dae"/>
      </geometry>
    </visual>
    
    <collision>
      <origin xyz="${-chassis_length*0.5} 0.0 ${chassis_height*0.5}" rpy="0 0.0 0"/>
      <!-- Modified to make collision more simple, chassis mesh replaced with box -->
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
  </link>



  <gazebo reference="${prefix}chassis">
      <material>Gazebo/Grey</material>
      <sensor name="imu_sensor" type="imu">
          <always_on>1</always_on>
          <update_rate>10</update_rate>
          <visualize>true</visualize>
          <topic>imu</topic>
      </sensor>
  </gazebo>

  
</robot>
