# Automatically generated by: ros2nix --output-as-nix-pkg-name --distro jazzy --fetch
{
  lib,
  buildRosPackage,
  fetchFromGitHub,
  ament-cmake,
  ament-lint-auto,
  ament-lint-common,
  fields2cover,
  nav2-ros-common,
  nav2-util,
  opennav-coverage,
  opennav-coverage-msgs,
  rclcpp,
  tinyxml-2,
}:
buildRosPackage rec {
  pname = "ros-jazzy-opennav-row-coverage";
  version = "0.0.1";

  src = fetchFromGitHub {
    owner = "open-navigation";
    repo = "opennav_coverage";
    rev = "d8ddc24064d294be07011d8200dfe2dbe17aeded";
    sha256 = "0gnlhn4hldkq6vl2vid124bkz0zz3g6f671wb7l5ycf3y51phvxx";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/opennav_row_coverage/";
  buildInputs = [ ament-cmake ];
  checkInputs = [
    ament-lint-auto
    ament-lint-common
  ];
  propagatedBuildInputs = [
    fields2cover
    nav2-ros-common
    nav2-util
    opennav-coverage
    opennav-coverage-msgs
    rclcpp
    tinyxml-2
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "A coverage server based on pre-defined rows";
    license = with lib.licenses; [ asl20 ];
  };
}
