# Automatically generated by: ros2nix --output-as-nix-pkg-name --distro jazzy --fetch
{
  lib,
  buildRosPackage,
  fetchFromGitHub,
  ament-cmake,
  ament-lint-auto,
  ament-lint-common,
  geometry-msgs,
  nav-msgs,
  nav2-behavior-tree,
  nav2-core,
  nav2-msgs,
  nav2-ros-common,
  nav2-util,
  opennav-coverage,
  opennav-coverage-bt,
  opennav-coverage-msgs,
  rclcpp,
  rclcpp-action,
}:
buildRosPackage rec {
  pname = "ros-jazzy-opennav-coverage-navigator";
  version = "0.0.1";

  src = fetchFromGitHub {
    owner = "open-navigation";
    repo = "opennav_coverage";
    rev = "d8ddc24064d294be07011d8200dfe2dbe17aeded";
    sha256 = "0gnlhn4hldkq6vl2vid124bkz0zz3g6f671wb7l5ycf3y51phvxx";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/opennav_coverage_navigator/";
  buildInputs = [ ament-cmake ];
  checkInputs = [
    ament-lint-auto
    ament-lint-common
    opennav-coverage
    opennav-coverage-bt
  ];
  propagatedBuildInputs = [
    geometry-msgs
    nav-msgs
    nav2-behavior-tree
    nav2-core
    nav2-msgs
    nav2-ros-common
    nav2-util
    opennav-coverage
    opennav-coverage-bt
    opennav-coverage-msgs
    rclcpp
    rclcpp-action
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "A navigator plugin for BT Navigator for coverage planning";
    license = with lib.licenses; [ asl20 ];
  };
}
