# Automatically generated by: ros2nix --output-as-nix-pkg-name --distro jazzy --fetch
{
  lib,
  buildRosPackage,
  fetchFromGitHub,
  ament-cmake,
  ament-lint-auto,
  ament-lint-common,
  builtin-interfaces,
  geometry-msgs,
  nav-msgs,
  nav2-msgs,
  nav2-util,
  rclcpp,
  rclcpp-action,
  rclcpp-lifecycle,
  rosidl-default-generators,
  tf2-ros,
}:
buildRosPackage rec {
  pname = "ros-jazzy-opennav-coverage-msgs";
  version = "0.0.1";

  src = fetchFromGitHub {
    owner = "open-navigation";
    repo = "opennav_coverage";
    rev = "d8ddc24064d294be07011d8200dfe2dbe17aeded";
    sha256 = "0gnlhn4hldkq6vl2vid124bkz0zz3g6f671wb7l5ycf3y51phvxx";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/opennav_coverage_msgs/";
  buildInputs = [ ament-cmake ];
  checkInputs = [
    ament-lint-auto
    ament-lint-common
  ];
  propagatedBuildInputs = [
    builtin-interfaces
    geometry-msgs
    nav-msgs
    nav2-msgs
    nav2-util
    rclcpp
    rclcpp-action
    rclcpp-lifecycle
    rosidl-default-generators
    tf2-ros
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "A set of ROS interfaces for complete coverage planning";
    license = with lib.licenses; [ asl20 ];
  };
}
