rosDistro: final: prev:
let
  # --- PACKAGE SETS AND OVERLAYS ---
  # ros2nix autogenerated package overlay location
  packagingOverlay = import ./nix-packages/overlay.nix;
  # set of patched packages fixing stuff to apply (eg fixes for broken ros2 package builds such as nav2)
  patchesOverlay = (import ./patches.nix rosDistro) final prev;
  # the full set of packages, with patches applied
  patchedPkgs = prev // patchesOverlay;

  rosPkgsOverlay =
    rosFinal: rosPrev:
    # use composeManyExtensions to "combine" the overlays in the order specified
    (prev.lib.composeManyExtensions [
      # add all the workspace packages to the output ros package set
      packagingOverlay
      (rosFinal: rosPrev: {
        /*
          as well as including all of them in a single attribute set to make package selection easier

          The intersection of the full custom package set and the workspace packages overlay
          selects the fully resolved packages out of the custom package set,
          getting us only the dev packages.

          That then gets merged with the colcon-ignore package so colcon doesn't try
          and build things from the (already built!) result symlink that nix build generates
        */
        devPackages = (builtins.intersectAttrs (packagingOverlay null null) rosFinal) // {
          inherit (prev) colcon-ignore; # always include colcon-ignore in dev packages
        };
        # additionally, override rviz by default to wrap it with nixGL since most people are on Ubuntu not NixOS
        # also provide native rviz with an alias
        rviz2-fixed = prev.writeShellScriptBin "rviz2-fixed" ''
          NIXPKGS_ALLOW_UNFREE=1 QT_QPA_PLATFORM=xcb QT_SCREEN_SCALE_FACTORS=1 nix run --impure "github:nix-community/nixGL" "${prev.lib.getExe rosPrev.rviz2}" -- "$@"
        '';
      })
    ] rosFinal rosPrev);
in
patchesOverlay
// {
  rosPackages = patchedPkgs.rosPackages // {
    ${rosDistro} = patchedPkgs.rosPackages.${rosDistro}.overrideScope rosPkgsOverlay;
  };
}
