# Automatically generated by: ros2nix --no-default
{ lib, buildRosPackage, ament-copyright, ament-flake8, ament-pep257, pythonPackages }:
buildRosPackage rec {
  pname = "ros-rolling-input-controllers";
  version = "0.0.0";

  src = ./.;

  buildType = "ament_python";
  checkInputs = [ ament-copyright ament-flake8 ament-pep257 pythonPackages.pytest ];

  meta = {
    description = "TODO: Package description";
    license = with lib.licenses; [ "TODO-License-declaration" ];
  };
}
