name: PlatformIO CI
on:
  push:
    branches-ignore:
      - gh-readonly-queue/** # ignore push actions triggered by merge queue
  pull_request:
  merge_group:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  changes:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      manual: ${{ github.event_name == 'workflow_dispatch'}}
      bms: ${{ steps.filter.outputs.bms }}
      status-ring: ${{ steps.filter.outputs.status-ring }}
      processing-plant: ${{ steps.filter.outputs.processing-plant }}
      rover-control-board: ${{ steps.filter.outputs.rover-control-board }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: .github/filters-firmware.yaml
  build-bms:
    runs-on: ubuntu-latest
    if: ${{ (needs.changes.outputs.bms != 'false') }}
    needs: changes
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: Build PlatformIO Project
        working-directory: ./firmware/battery-management-system
        run: pio run
  build-status-ring:
    runs-on: ubuntu-latest
    if: ${{ (needs.changes.outputs.status-ring != 'false') }}
    needs: changes
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: Build PlatformIO Project
        working-directory: ./firmware/status-ring
        run: pio run
  build-processing-plant:
    runs-on: ubuntu-latest
    if: ${{ (needs.changes.outputs.processing-plant != 'false') }}
    needs: changes
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: Build PlatformIO Project
        working-directory: ./firmware/processing-plant
        run: pio run
  build-elevator-module:
    runs-on: ubuntu-latest
    if: ${{ (needs.changes.outputs.processing-plant != 'false') }}
    needs: changes
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: Build PlatformIO Project
        working-directory: ./firmware/elevator-module
        run: pio run
  build-rover-control-board:
    runs-on: ubuntu-latest
    if: ${{ (needs.changes.outputs.rover-control-board != 'false') }}
    needs: changes
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: Build PlatformIO Project
        working-directory: ./firmware/rover-control-board
        run: pio run
